# Usa una imagen base de Ubuntu
FROM ubuntu:latest

# Actualiza los paquetes y luego instala Node.js y npm
RUN apt-get update && \
    apt-get install -y nodejs npm && \
    npm install -g npm@latest && \
    ln -s /usr/bin/nodejs /usr/bin/node

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia los archivos de la aplicación
COPY . .

# Instala las dependencias
RUN npm install

# Expone el puerto en el que corre tu aplicación
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["node", "server.js"]
